services:
  toolbox:
    image:  us-central1-docker.pkg.dev/database-toolbox/toolbox/toolbox:0.9.0
    hostname: toolbox
    platform: linux/arm64
    ports:
      - "5000:5000"
    volumes:
      - ./config:/config
    command: [ "toolbox", "--tools-file", "/config/toolbox.yaml", "--address", "0.0.0.0"]
    networks:
      - toolbox-network
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:latest
    hostname: db
    platform: linux/arm64
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d toolbox_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=toolbox_db
    networks:
      - toolbox-network
networks:
  toolbox-network: